buyer/urls.py
from django.urls import path
from buyer import views

app_name = 'buyer'

urlpatterns=[
    path('buyerapp/',views.buyerapp),
    path('proddetails/<int:id>/',views.proddetails,name ='proddetails'),
    path('cartitems/',views.cartitems),
    path('removecart/<int:id>/',views.removecart,name='removecart'),
    path('buyitems/<int:id>/',views.buyitems,name='buyitems'),
    path('addDeliveryDetails/<int:id>/',views.addDeliveryDetails,name='addDeliveryDetails'),
    path('history/',views.history),
    path('order/',views.order),
    path('notification/',views.notification),
    path('buyerprofile/',views.buyerprofile),
    path('addressform/',views.addAddress),
    path('checkout/<int:id>/',views.checkout,name='checkout'),
    path('buyallproduct/',views.buyallproduct),
    path('checkoutallprod/',views.checkoutallprod),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('register/',views.register),
    path('login_call/',views.login_call),
    path('logout_call/',views.logout_call),
    path('buyer/',include("buyer.urls")),
    path('seller/',include("seller.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from seller import views

app_name = 'seller'

urlpatterns=[
    path('sellerapp/',views.sellerapp),
    path('addproduct/',views.addproduct),
    path('addcategory/',views.addcategory),
    path('addedproduct/',views.addedproduct),
    path('modifyproduct/<int:id>/',views.modifyproduct,name='modifyproduct'),
    path('sellernotifications/',views.sellernotifications),
    path('createnotifications/',views.createnotifications),
    path('sellerorders/',views.sellerorders),
    path('sellershippcall/<int:id>',views.sellershippcall,name = 'sellershippcall'),
]

templates/addedproduct.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block navigation %}

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Ecommerce App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/seller/sellerapp/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addproduct/">Add Product</a>
          </li>
					<li class="nav-item">
            <a class="nav-link" href="/seller/addcategory/">Add Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addedproduct/">Added Products</a>
          </li>
					<li class="nav-item">
						<a class="nav-link" href="/seller/sellernotifications/">Notifications</a>
					</li>
					<li>
            <a class="nav-link" href="/seller/sellerorders/">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout_call/">Logout</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block mainblock %}
<br>
<div class="row">
	{% for i in prod %}
	<br>
	<div class="col-md-4 card" style="width: 18rem;">
	  <img class="card-img-top" src="{{ i.product_img.url }}" alt="product img!">
	  <div class="card-body">
	    <h5 class="card-title">{{ i.product_name }}</h5>
	    <p class="card-text">Rs {{ i.product_price }}/-</p>
	    <a href="{% url 'seller:modifyproduct' id=i.id %}" class="btn btn-primary">Modify</a>
	  </div>
	</div>
	<br>
	{% endfor %}
</div>
<br>
{% endblock %}

templates/addproduct.html
{% extends 'base.html' %}


{% block navigation %}

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Ecommerce App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/seller/sellerapp/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addproduct/">Add Product</a>
          </li>
					<li class="nav-item">
            <a class="nav-link" href="/seller/addcategory/">Add Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addedproduct/">Added Products</a>
          </li>
					<li class="nav-item">
						<a class="nav-link" href="/seller/sellernotifications/">Notifications</a>
					</li>
					<li>
            <a class="nav-link" href="/seller/sellerorders/">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout_call/">Logout</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block mainblock %}

	<br><br>
	<h1>Add Product</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<label>Product Name: </label><input type="text" name="pname" class="form-control"><br>

		<label>Description: </label><input type="text" name="desc" class="form-control"><br>

		<label>Price: </label><input type="number" name="price" class="form-control" class="form-control"><br>

		<label>Image: </label><input type="file" name="fil"><br><br>

		<label>Quantity: </label><input type="number" name="qty" class="form-control"><br>

		<label for="">Category:</label><br>
		<select name="catid" class="form-control">
		{% for i in lis %}
			<option value="{{i.cat}}">{{i.cat}}</option>
		{% endfor %}
		</select><br>

		<!--<input type="hidden" name="uname" value="{{request.user}}">-->

		<label>Save Date: </label><br><input type="text" name="sav"><br>

		<label>modified Date: </label><br><input type="text" name="mod"><br>

		<br><input type="submit" value="Add Product" class="btn-primary"><br>

	</form>
	<br><br>
{% endblock %}

templates/addressform.html
{% extends 'buyerside.html' %}

{% block buyerpro %}
<div class="w3-container w3-padding">
  <form action="/buyer/addressform/"  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ afrom.as_p }}
    <input type="submit" name="submit" value="Submit" style="width:196px;" class="w3-red">
  </form>
</div>
<br>
{% endblock %}


<!--
  <input type="text" name="hno" value="" placeholder="House no." required>
  <input type="text" name="street" value="" placeholder="Street" required>
  <input type="text" name="ward" value="" placeholder="Ward"  required>
  <input type="text" name="city" value="" placeholder="City" required>
  <input type="text" name="dist" value="" placeholder="District" required>
  <input type="text" name="pin" value="" placeholder="Pin" required>
  <input type="text" name="state" value="" placeholder="State"  required>
-->

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Ecommerce App</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
</head>

<body>

  <!-- Navigation -->
  {% block navigation %}

  {% endblock %}

  <!-- Page Content -->
  <div class="container">

    <!-- Jumbotron Header -->
    {% block mainblock %}
    {% endblock %}

    {% block sellernotifications %}
    {% endblock %}

    {% block createnotifications %}
    {% endblock %}

    {% block sellerorders %}
    {% endblock %}

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/baseone.html
{% extends 'basemain.html' %}

{% block maincontent %}
<!-- Jumbotron Header -->
<header class="jumbotron my-4">
  <h1 class="display-3">A Warm Welcome!</h1>
  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
  <a href="#" class="btn btn-primary btn-lg">Call to action!</a>
</header>
{% endblock %}

{% block mcontent %}
<div class="col-lg-3 col-md-6 mb-4">
  <div class="card h-100">
    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
    </div>
    <div class="card-footer">
      <a href="#" class="btn btn-primary">Find Out More!</a>
    </div>
  </div>
</div>

<div class="col-lg-3 col-md-6 mb-4">
  <div class="card h-100">
    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
    </div>
    <div class="card-footer">
      <a href="#" class="btn btn-primary">Find Out More!</a>
    </div>
  </div>
</div>

<div class="col-lg-3 col-md-6 mb-4">
  <div class="card h-100">
    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
    </div>
    <div class="card-footer">
      <a href="#" class="btn btn-primary">Find Out More!</a>
    </div>
  </div>
</div>

<div class="col-lg-3 col-md-6 mb-4">
  <div class="card h-100">
    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
    </div>
    <div class="card-footer">
      <a href="#" class="btn btn-primary">Find Out More!</a>
    </div>
  </div>
</div>
{% endblock %}

templates/buyallproduct.html
{% extends 'buyerside.html' %}
{% load staticfiles %}


{% block buyall %}
<div class="w3-container w3-padding">
  <h3>Review</h3>
  <div class="w3-container">
    <form action="/buyer/buyallproduct/" method="post">
      {% csrf_token %}
      <label for="selone">Address</label><br>
      <select  name="address" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
        {% for i in address %}
        <option value="{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}">{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}</option>
        {% endfor %}
      </select>
      <br><br>
      {% for i in obj %}
        <div class="w3-container w3-padding w3-border">
          <p><b>{{ i.prodcartid.product_name }}</b></p>
          <img src="{{ i.prodcartid.product_img.url }}" alt="img" height="150" width="150">
          <br>
          <p>Description : {{ i.prodcartid.product_desc }}</p>
          <p>Stock : {{ i.prodcartid.product_avail }} items</p>
          <p>Retailer : {{ i.prodcartid.added_by_seller }}</p>
          <p>Select Quantity</p>
          <select  name="selc" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
        </div>
        <input style="display:none;" type="number" name="ide" value="{{ i.id }}">
        <hr>
      {% endfor %}
      <p>Payment mode</p>
      <select  name="pay" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
        <option value="Online Wallet">Online Wallet</option>
        <option value="Cash on delivery">Cash on delivery</option>
      </select>
      <br>
      <br>
      <input type="submit" name="sub" value="Reviewed" class="w3-red w3-padding">
      <br><br>
    </form>
  </div>
</div>
{% endblock %}

templates/checkout.html
{% extends 'buyerside.html' %}


{% block checkout %}
<div class="w3-container w3-padding">
  <div class="w3-container w3-padding">
    <b>{{ product.product_name }}</b>
    <br>
    <img src="{{ product.product_img.url }}" alt="img" height="130" width="150">
    <br>
    <br><br>
    <b class="w3-red w3-padding">Price: Rs {{ product.product_price }} /-</b>
    <br><br>
    <br>
    <b>Description : {{ product.product_desc }}</b>
    <br>
    <b>Shipping address : {{ address }}</b><br>
    <b>Shipping quantity : {{ quantaty }}</b><br>
    <b>Payment mode : {{ payment}}</b><br>
    <b>Delivery : 2 - 3 days</b>
    <br>
    <br>
    <b>Total Cost : Rs {{ total }} /-</b>
    <br>
    <form action="{% url 'buyer:checkout' id=ide %}" method="post">
      {% csrf_token %}
      <input type="submit" name="sub" value="Checkout" class="w3-red" style="width:150px;height:36px">
    </form>
  </div>
</div>
{% endblock %}

templates/history.html
{% extends 'buyerside.html' %}


{% block history %}
<br>
<div class="w3-container">
  <div class="w3-container">
    <div class="w3-left">
      <form action="/buyer/order/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" name="order" value="Order History" class="w3-red" style="border:1px solid #CAFAFE;">
      </form>
    </div>
    <div class="w3-right">
      <form action="/buyer/notification/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" name="notify" value="Notifications" class="w3-red" style="border:1px solid #CAFAFE;">
      </form>
    </div>
  </div>
  <div class="w3-container">


    {% block order %}
    {% endblock %}

    {% block notification %}
    {% endblock %}
  </div>

</div>
<br>
{% endblock %}

templates/login_call.html
{% extends 'basemain.html' %}
{% block logcdn %}
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <h3 class="text-center">Log In</h3>
    <form method="post" class="form-group" enctype="multipart/form-data">
      {% csrf_token %}
      <label for="">Username</label>
      <br>
      <input type="text" name="usernm" value="" class="form-control">
      <br>
      <label for="">Password</label>
      <br>
      <input type="password" name="passwd" value="" class="form-control">
      <br>
      <input type="submit" name="" value="Log In" class="form-control">
    </form>
  </div>
  <div class="col-md-4"></div>
</div>
{% endblock %}

<!--
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <input type="text" name="usernm" placeholder="Username" class="form-control">
  </div>
  <div class="col-md-4"></div>
</div>
<br>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <input type="text" name="passwd" placeholder="********" class="form-control">
  </div>
  <div class="col-md-4"></div>
</div>
<br>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <input type="submit" value="Log In" class="form-control" style="background-color:green;color:white;">
  </div>
  <div class="col-md-4"></div>
</div>
-->

templates/order.html
{% extends 'history.html' %}

{% block order %}
<div class="w3-container">
<h3>Order history</h3>
{% for i in obj %}
  {{ i.tim }}
  <div class="w3-container w3-padding w3-border">
    <div class="w3-left">
      <p><b>{{ i.productname }}</b></p>
      <img src="{{ i.productimage.url }}" alt="img" height="100" width="100">
    </div>
    <div class="w3-right">
      <table class="w3-table">
        <tr>
          <td>Price</td>
          <td>{{ i.productprice }}</td>
        </tr>
        <tr>
          <td>Quantity</td>
          <td>{{ i.productqty }}</td>
        </tr>
        <tr>
          <td>Mobile</td>
          <td>{{ i.buyermobile }}</td>
        </tr>
        <tr>
          <td>Address</td>
          <td>{{ i.buyeraddress }}</td>
        </tr>
        <tr>
          <td>Seller</td>
          <td>{{ i.userid }}</td>
        </tr>
        <tr>
          <td>Status</td>
          {% if i.status == "ordered" %}
            <td style="color:blue">{{ i.status }}</td>
          {% endif %}
          {% if "shipped" in i.status %}
            <td style="color:orange">{{ i.status }}</td>
          {% endif %}
          {% if "delivered" in i.status %}
            <td style="color:green">{{ i.status }}</td>
          {% endif %}
          {% if i.status == "out of stock" %}
            <td style="color:red">{{ i.status }}</td>
          {% endif %}
        </tr>
      </table>
    </div>
    <div class="w3-container">
      <a href="#"><button type="button" name="button" class="w3-black">Remove order</button></a>
      {% if i.status != "delivered" %}
      <a href="#"><button type="button" name="button" class="w3-black">Cancel order</button></a>
      {% endif %}
    </div>
  </div>
  <br>
{% endfor %}
</div>
{% endblock %}

templates/prodDeliveryDetails.html
{% extends 'buyerside.html' %}

{% block prodDeliveryDetail %}
<div class="w3-container">
  <h3>Review</h3>
  <div class="w3-container">
    {{ product.product_name }}
    <br>
    <img src="{{ product.product_img.url }}" alt="img" height="130" width="150">
    <p>Description : {{ product.product_desc }}</p>
    <p>Items in stock : {{ product.product_avail }} items</p>
    <p>Retailer : {{ product.added_by_seller }}</p>
    <br>
  </div>
  <form  action="{% url 'buyer:addDeliveryDetails' id=idy %}" method="post">
    {% csrf_token %}
    <label for="selone">Address</label><br>
    <select  name="address" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
      {% for i in address %}
      <option value="{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}">{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}</option>
      {% endfor %}
    </select>
    <br><br>
    <label for="seltwo">Quantaty</label><br>
    <select  name="sel" style="width:80%;border:2px solid orange;height:35px;" id="seltwo" required>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
    </select>
    <br><br>
    <label for="selthree">Payment Option</label><br>
    <select  name="pay" style="width:80%;border:2px solid orange;height:35px;" id="selthree" required>
      <option value="Online Wallet">Online Wallet</option>
      <option value="Cash on delivery">Cash on delivery</option>
    </select>
    <br>
    <br>
    <input type="submit" name="" value="Reviewed" class="w3-red w3-padding">
  </form>
</div>
<br>
{% endblock %}

templates/regist.html
{% extends 'basemain.html' %}

{% block contextdelevery %}
<h3 class="text-center">Sign Up</h3>
<form method="post" class="form-group" enctype="multipart/form-data">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      {% csrf_token %}
      {{ form1.as_p }}
      {% csrf_token %}
      {{ form2.as_p }}
      <input type="submit" name="" value="Sign Up">
      <br>
      <br>
      <br>
      <h5>If already registered try <a href="/login_call">Login</a> </h5>
    </div>
    <div class="col-md-4"></div>
  </div>
</form>
{% endblock %}

templates/sellernotifications.html
{% extends 'base.html' %}


{% block navigation %}

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Ecommerce App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/seller/sellerapp/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addproduct/">Add Product</a>
          </li>
					<li class="nav-item">
            <a class="nav-link" href="/seller/addcategory/">Add Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addedproduct/">Added Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/sellernotifications/">Notifications</a>
          </li>
					<li>
            <a class="nav-link" href="/seller/sellerorders/">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout_call/">Logout</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block sellernotifications %}
<div class="container">
  <div class="">
		<br>
		<br>
    <div>
    	<h5 class="text-center" style="float:left">Notifications</h5>
			<a href="/seller/createnotifications/" style="float:right;text-decoration:none;"><button type="button" name="button" style="color:#CAFAFE;background-color:black;border:1px solid #CAFAFE;" class="form-control">Create</button></a>
    </div>
		<br>
    <br>
    {% for i in obj %}
				{{i.tim}}
      <div class="container" style="padding:10px;border:0.5px solid #ccc">
        {{ i.message }}
      </div>
			<br>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/viewproduct.html
{% extends 'buyerside.html' %}
{% load staticfiles %}

{% block viewproduct %}
<div class="w3-container">
  <a href="/buyer/buyerapp/"><button type="button" name="button" style="color:white;background-color:black;">Go back</button></a>
</div>
<br><br>
<div class="w3-display-container w3-container text-center">
  <img src="{{ pro.product_img.url }}" alt="Jeans" style="height: 5%;width:30%;">
  <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
  </div>
</div>
<div  class="w3-container w3-xlarge">
  <p style="background-color:black;color:#CAFAFE;" class="w3-left">Price : Rs {{ pro.product_price }} /- </p>
  <p style="background-color:black;color:#CAFAFE;margin-left:1%;" class="w3-left"> Offer : 50% Off</p>
</div>
<div class="w3-container w3-xlarge">
  {{ pro.product_name }}
  <p>Description : {{ pro.product_desc }}</p>
  <p>Items in stock : {{ pro.product_avail }} items</p>
  <p>Retailer : {{ pro.added_by_seller }}</p>
  <p>Payment Options : --------</p>
  <p>Delevery options : ---------</p>
  <br><br>
  <form method="post">
    {% csrf_token %}
    <a href="#"><input type="submit" name="" value="Add to cart" style="color:#CAFAFE;background-color:black;border:2px solid #CAFAFE;"></a>
  </form>
</div>
<br><br>
{% endblock %}